# Site
name: "CivicTech Waterloo Region Blog"
title: "CivicTech Waterloo Region Blog"
description: "CivicTech Waterloo Region Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: https://civictechwr.github.io
baseurl: /blog
google_analytics: 'UA-xxxxxxxx-1'
disqus: ' '
mailchimp-list: ' '
include: ["_pages"]
permalink: /:title/
email: civictechwr@gmail.com

# Authors
authors:
  Mohamed Fouda:
    name: Mohamed Fouda
    display_name: Mohamed Fouda
    avatar: 'assets/images/mohamed-fouda.png'
    email: civictechwr@gmail.com
    web: https://www.civictechwr.org/
    twitter: https://twitter.com/civictechwr
    description: "Author of CivicTech Waterloo Region Blog"
  Apurva Bhatia:
    name: Apurva Bhatia
    display_name: Apurva Bhatia    
    avatar: 'assets/images/apurva-bhatia.png'
    email: civictechwr@gmail.com
    web: https://www.civictechwr.org
    twitter: https://twitter.com/wowthemesnet
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."
  Kristina:
    name: Kristina
    display_name: Kristina    
    avatar: 'assets/images/kristina.png'
    email: civictechwr@gmail.com
    web: https://www.civictechwr.org
    twitter: https://twitter.com/wowthemesnet
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

