# Site
name: "CivicTech Waterloo Region Blog"
title: "CivicTech Waterloo Region Blog"
description: "Join our community of tech enthusiasts and designers working together to solve local challenges in the Waterloo region"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: https://civictechwr.github.io
baseurl: /blog
google_analytics: 'UA-xxxxxxxx-1'
disqus: ' '
mailchimp-list: ' '
include: ["_pages"]
permalink: /:title/
email: civictechwr@gmail.com

# Authors
authors:
  foudamo:
    name: Mohamed Fouda
    display_name: Mohamed Fouda
    avatar: 'https://avatars.githubusercontent.com/u/6817956?v=4'
    email: civictechwr@gmail.com
    web: https://github.com/foudamo
    twitter: https://twitter.com/civictechwr
    description: "Product Manager by day. Civictechwr Organizer by night"
  apurvakb:
    name: Apurva Banastarker
    display_name: Apurva Banastarker    
    avatar: 'https://avatars.githubusercontent.com/u/61383076?v=4'
    email: civictechwr@gmail.com
    web: https://github.com/apurvakb
    twitter: https://twitter.com/civictechwr
    description: "Digital Marketing"
  kristinataylor:
    name: Kristina Taylor
    display_name: Kristina Taylor    
    avatar: 'https://avatars.githubusercontent.com/u/10520385?v=4'
    email: civictechwr@gmail.com
    web: https://www.linkedin.com/in/kristina-taylor-48273427/
    twitter: https://twitter.com/civictechwr
    description: "Product Manager"
  dredre:
    name: Andre Levesque 
    display_name: Andre Levesque
    avatar: 'https://avatars.githubusercontent.com/u/169505867?v=4'
    email: civictechwr@gmail.com
    web: https://github.com/BreakableHoodie
    twitter: https://twitter.com/civictechwr
    description: "IT veteran with 20+ years' experience in system administration and cybersecurity. AWS certified professional who loves problem-solving and tinkering."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

